server {
    listen 8099;
    allow 172.30.32.2;
    deny all;

    location / {
        proxy_pass http://127.0.0.1:2021;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        # Disable compression so Nginx can filter all file types
        proxy_set_header Accept-Encoding "";

        # Broaden sub_filter to cover ALL file types
        sub_filter_types *;
        sub_filter_once off;

        # Replace absolute root paths with the dynamic Ingress prefix
        sub_filter 'href="/' 'href="$http_x_ingress_path/';
        sub_filter 'src="/' 'src="$http_x_ingress_path/';
        sub_filter 'url("/' 'url("$http_x_ingress_path/';
        sub_filter '/api/' '$http_x_ingress_path/api/';
        sub_filter '"/login' '"$http_x_ingress_path/login';
        sub_filter '\'/login' '\'$http_x_ingress_path/login';
        sub_filter '"/sw.js' '"$http_x_ingress_path/sw.js';
        sub_filter '\'/sw.js' '\'$http_x_ingress_path/sw.js';
        sub_filter '"/assets/' '"$http_x_ingress_path/assets/';
        sub_filter '\'/assets/' '\'$http_x_ingress_path/assets/';
        # The above paths enable the homepage of Donetick to load.
        # The below still need to be tested and potentially added.
        # sub_filter '/assets/' '$http_x_ingress_path/assets/';
        # sub_filter '"/circles' '"$http_x_ingress_path/circles';
        # sub_filter '"/devices' '"$http_x_ingress_path/devices';
        # sub_filter '"/chores' '"$http_x_ingress_path/chores';
        # sub_filter '"/labels' '"$http_x_ingress_path/labels';

        # sub_filter '"/things' '"$http_x_ingress_path/things';
        # sub_filter '"/users' '"$http_x_ingress_path/users';

    }
}
